import { readFile, writeFile } from "node:fs/promises";

const [gateFile, output] = process.argv.slice(2);
const gate = JSON.parse(await readFile(gateFile, "utf8"));
const lines = [
  "## AI review gate",
  "",
  `**Status:** ${gate.status.toUpperCase()}`,
  `**Summary:** ${gate.summary}`,
  "",
  "| Reviewer | Mode | Status |",
  "|---|---|---|",
  ...gate.reviewers.map((item) => `| ${item.reviewer} | ${item.mode} | ${item.status} |`)
];
if (gate.blocking_findings.length) {
  lines.push("", "### Blocking findings");
  for (const finding of gate.blocking_findings.slice(0, 30)) {
    const location = finding.file ? ` (${finding.file}${finding.line ? `:${finding.line}` : ""})` : "";
    lines.push(`- **${finding.severity}** ${finding.category}${location}: ${finding.message}`);
  }
}
if (gate.missing_reviewers?.length) {
  lines.push("", "### Missing required reviews");
  for (const reviewer of gate.missing_reviewers) lines.push(`- ${reviewer}`);
}
lines.push("", "Generated by the provider-neutral review contract in `review/`.");
await writeFile(output, lines.join("\n") + "\n");
